subroutine sub1(c1,c2,i,n)
include "xmp_coarray.h"
include "mpif.h"
implicit  REAL*4(A-H,O-Z)
REAL*8 A(n)
REAL*4 B(n)
DIMENSION c2(n),I(n)
REAL*4  CA(10)[*]
PARAMETER (MAXDOM = 10000)
INTEGER*4 MSGIDS(MAXDOM),MSGSTS(MPI_STATUS_SIZE,MAXDOM)
CA(1)=1.0
CA(1)[1]=c1
write(*,*) CA,I
call DDCOMX(1,1,I,I,876024,I,I,876024,B,B,B,876024,1,II,B,B,876024)
end subroutine sub1

      SUBROUTINE DDCOMX(IPART,IDIM,LDOM,NBPDOM,NDOM,IPSLF,IPSND,MBPDOM,FX,FY,FZ,NP,IUT0,IERR,BUFSND,BUFRCV,MAXBUF)
      INCLUDE 'mpif.h'
      INCLUDE 'xmp_coarray.h'
      IMPLICIT REAL*4(A-H,O-Z)
!CTTDEBG
      REAL*8 DFX(NP),DFY(NP),DFZ(NP)
!CTTDEBG
      DIMENSION LDOM(NDOM),NBPDOM(NDOM),IPSLF(MBPDOM,NDOM),IPSND(MBPDOM,NDOM), FX(NP),FY(NP),FZ(NP),BUFSND(MAXBUF),BUFRCV(MAXBUF)
      REAL*4 BUFRCV2(10)[*]
      REAL*4 TMPSND
      REAL*4 TMPRCV
!
      PARAMETER ( MAXDOM = 10000 )
      INTEGER*4 MSGIDS(MAXDOM),MSGSTS(MPI_STATUS_SIZE,MAXDOM)
!
!
      CHARACTER*60 ERMSGB  / ' ## SUBROUTINE DDCOMX: FATAL     ERROR OCCURRENCE; RETURNED' /
      CHARACTER*60 EREXP1  / ' DIMENSION SIZE OF INTERNAL      ARRAYS IS NOT SUFFICIENT  ' /
      CHARACTER*60 EREXP2  / ' DIMENSION SIZE OF PASSED BUFFER ARRAYS IS NOT SUFFICIENT  ' /
      CHARACTER*60 EREXP3  / ' RECEIVED NODE NUMBER IS OUT OF THE GLOBAL NODE NUMBER     ' /
      CALL MPI_COMM_RANK(MPI_COMM_WORLD,ITASK,IERR)
!      IF (ITASK.eq.0) PRINT *,"CALL DDCOMX"
#ifdef USE_BARRIER
      call MPI_BARRIER(MPI_COMM_WORLD, IERR)
#endif
      TMPRCV=1.0
      call xmpf_coarray_msg(1)
      PRINT *,"ITASK=",ITASK
      BUFRCV2(1)[1]=TMPRCV
      PRINT *,"ITAS K=",ITASK
      END SUBROUTINE DDCOMX
